### ISSUE TITLE
SmartyException error

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#1]
Downloaded the master branch, when trying to access the site I get:

Unkown resource type 'findExtends'

Fatal error: Uncaught exception 'SmartyException' with message 'Unkown resource type 'findExtends'' in /var/www/mobile/lib/smarty/sysplugins/smarty_internal_template.php:757
Stack trace:
#0 /var/www/mobile/lib/smarty/sysplugins/smarty_internal_template.php(444): loadTemplateResourceHandler(string)
#1 /var/www/mobile/lib/smarty/sysplugins/smarty_internal_template.php(567): renderTemplate()
#2 /var/www/mobile/lib/smarty/Smarty.class.php(336): getRenderedTemplate()
#3 /var/www/mobile/lib/smarty/Smarty.class.php(382): fetch(string, NULL, NULL, NULL, boolean)
#4 /var/www/mobile/lib/TemplateEngine.php(369): display(string, NULL, NULL)
#5 /var/www/mobile/lib/WebModule.php(1165): displayForDevice(string)
#6 /var/www/mobile/www/index.php(234): displayPage()
#7 {main}

thrown in /var/www/mobile/lib/smarty/sysplugins/smarty_internal_template.php on line 757

**Comment by akinspe** [comment]
When pulling from Kurogo, please make sure you clear out your smarty cache in SITE_DIR/cache/smarty. Simply remove the smarty and minify folders. they will automatically get rebuilt. We may have a more automated utility to do this on upgrade in the future. Please report if this fixes the issue.

**Comment by bpayst** [comment]
Yes, that cleared up the smarty error, but now I'm getting Unable to create file download, directory not writable. I've chowned the site dir to the web server user, is there another directory that needs different permissions?

```
 Fatal error: Uncaught exception 'Exception' with message 'Unable to create file download, directory not writable' in     /var/www/mobile/lib/ConfigFile.php:122
Stack trace:
#0 /var/www/mobile/lib/ConfigFile.php(173): createDefaultFile(string, string)
#1 /var/www/mobile/lib/ModuleConfigFile.php(19): loadFileType(string, string, integer)
#2 /var/www/mobile/app/modules/download/DownloadWebModule.php(7): factory(string, string)
#3 /var/www/mobile/app/modules/home/HomeWebModule.php(53): appDownloadText(string)
# 4 /var/www/mobile/lib/WebModule.php(1072): initializeForPage()
#5 /var/www/mobile/lib/WebModule.php(1162): setPageVariables()
#6 /var/www/mobile/www/index.php(234): displayPage()
#7 {main}
thrown in /var/www/mobile/lib/ConfigFile.php on line 122
```

**Comment by akinspe** [comment]
Actually you discovered a bug in the default file loading code. Please pull master again and try again. Also please post new issues as separate issues. I will close this one since the smarty error has been fixed.

**Comment by bpayst** [comment]
I was able to remove the error by creationg a /media directory in the site directory, but I'll pull the code again.

**Comment by bpayst** [comment]
updated master fixed both issues
