### ISSUE TITLE
Error in KML file search

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#12]
Fatal error: Call to undefined method KMLPlacemark::getListItems() in /var/www/mobile/lib/Maps/MapDataController.php on line 186

while searching against a KML file. The list of points is returned, by trying to access the map location results in this error

**Comment by akinspe** [comment]
Please post copy of offending KML file to kurogo-dev mailing list and reference Issue 12

**Comment by bpayst** [comment]
Done.

**Comment by sonya** [comment]
I believe this problem was fixed in commit 91e6787ec13ac0b7e3fc62908f93d349fa67f6ee.  The code involved in getListItems is kind of scary, so we might discover other related problems, but searching through the KML file you posted should work for now.

**Comment by bpayst** [comment]
Yes, I can confirm this file is working correctly now. Thanks!
