### ISSUE TITLE
Included/Extended Template Paths on Windows

### ISSUE THREAD

**Issue by conover** [modolabs/Kurogo-Mobile-Web#15]
The paths being computed for including and extending templates in the smartyPrefilterHandleIncludeAndExtends method in lib/TemplateEnging.php are not being escaped properly. I had to add a \ -> \\ string replacement to both path variable assignments in that method to get the Kurogo to work. Doing the escaping there might not be the correct place to fix this but it fixed the immediate issue for me.

**Comment by zootsuitbrian** [comment]
Hello Chris,
  We noticed a similar or possibly identical issue a few days ago.  We believe the following commit https://github.com/modolabs/Kurogo-Mobile-Web/commit/d117018079c8fa0fa3dfe37582c2fff76d2bb173 fixes this issue, let us know if this does indeed fix the issue you are seeing?

**Comment by conover** [comment]
That seems to solve the problem as well. Thanks
