### ISSUE TITLE
People search - map

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#19]
the search results from the people module that are enabled to be mapped produce unreliable results, for example, my entry ends up with 01 Teague Residence Hall $ CB 5510 $ Chapel Hill, NC 27599-5510 $ USA

It would eb nice to have some way to tweak the filter for the results. In our case, and likely on many campuses, the building name is going to be in the map file and in the search results, but the street address and room number are likely not going to be

**Comment by akinspe** [comment]
There is a mechanism to handle that.  In the config/people/page-detail.ini add a urlfunc value to the map/location entry. This is a function can filter the value stored in the LDAP entry. Please post on the kurogo-dev list and I will respond with the full details so others can more easily share in the solution to this common problem. (it's not well documented)
