### ISSUE TITLE
Campus Map feeds

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#2]
When you only have one map group configured, you get an error when selecting the "browse by" drop down. For those of us with only one campus, it would be nice if this could degrade gracefully and not show the drop down if there is only one group. Not a huge deal, just reporting it.

```
 Invalid category path for multiple feed groups

 Fatal error: Uncaught exception 'Exception' with message 'invalid category path for multiple feed groups' in  /var/www/mobile/app/modules/map/MapWebModule.php:351
Stack trace:
#0 /var/www/mobile/app/modules/map/MapWebModule.php(714): getDataController(array, array)
#1 /var/www/mobile/lib/WebModule.php(1072): initializeForPage()
#2 /var/www/mobile/lib/WebModule.php(1162): setPageVariables()
#3 /var/www/mobile/www/index.php(234): displayPage()
#4 {main}
thrown in /var/www/mobile/app/modules/map/MapWebModule.php on line 351
```

**Comment by akinspe** [comment]
This issue actually occured with multiple feed groups as well. It has been fixed in https://github.com/modolabs/Kurogo-Mobile-Web/commit/00c72851df1e842bda7818d89c0ecc9fd4154651

**Comment by akinspe** [comment]
So I misunderstood your other point. You probably mean that not only do you only have 1 "feed group" you also only have 1 "feed" which means the drop down shouldn't even show up. That has been fixed in https://github.com/modolabs/Kurogo-Mobile-Web/commit/24276c9c0e20ba17fc7912f99a52e76c8e3be2c5
