### ISSUE TITLE
Calendar Detail Page Issues

### ISSUE THREAD

**Issue by eebs** [modolabs/Kurogo-Mobile-Web#20]
There seems to be come CSS issues with the Calendar detail page. It seems there should be some borders around the various fields that are pulled in from the event, but they are missing as seen here:

http://eebs-tech.com/calendar/detail?calendar=calendarofevents&type=static&id=5978911&time=1307394000

This Harvard event shows what I believe should be correct:

http://m.harvard.edu/calendar/detail?id=http%3A%2F%2Fuid.trumba.com%2Fevent%2F94466376 

It is hard for me to be sure because the default Universitas events don't have much additional information that would cause this bug to occur. I switched my site to Universitas, used our iCal feed, and the CSS issue was still present, so I think that rules out any CSS changes that I could have made in my site. I know the Universitas CSS is unchanged because I cloned with git.

There is also a second issue also on the Calendar Detail page. The last matching field is placed into the 'legend' block in calendar/templates/detail.tpl. This causes the page to look odd if the last matching field happens to be a description rather than a list of categories as is the case with the Harvard page. Please reference the above URLs as examples.

If I can be of any assistance with fixing this let me know.

-Eebs
UVM Communications

**Comment by akinspe** [comment]
Can you update and see if this issue still persists?

**Comment by eebs** [comment]
Pulled in most recent changes (including 1.2), but the borders are still not showing up.

http://m.uvm.edu/calendar/list?type=static&calendar=calendarofevents&limit=30 (old link did not work anymore)

**Comment by akinspe** [comment]
Is this still an issue?

**Comment by eebs** [comment]
It is still an issue, but I have written some simple css to work around it. I am happy to use my css and close this issue if no one else is reporting the problem, and if you're unable to reproduce it.

**Comment by eebs** [comment]
After some discussion we found it is an problem in our theme, which was based on the default theme from before Kurogo 1.2. Issue closed.
