### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#21]
[07-Jun-2011 15:15:01] PHP Fatal error:  Call to a member function getTitle() on a non-object in /var/www/mobile/app/modules/map/MapWebModule.php on line 773

URL that produces this error:

http://m.unc.edu/map/detail?featureindex=Carr+Building&category=campus%3A0%3A0&_b=%258B%25AEV%252AQ%25B2R%25F2M%252CP%25D2Q%25CAA0%250B%2580%25AC%25CC%25BC%2594%25D4%250A%2B%253B%2511%25C8V%25AA%25D5%2581%25A8%250CNM%252CJ%25CE%2580%2529%2586%25F0%2514%2582R%258BKsJ%258A%25A1%25FA%258AaJ%2540%251A%25D32sJR%258Bl%259D%2513%258B%258A%2594jc%2501

inconsistent as most searches /. results work fine.

this is against an ArcInfo map server

**Comment by bpayst** [comment]
seems to be specific to the ArcGIS data controller, KML works fine

**Comment by bpayst** [comment]
note that the above URL no longer works as I have switched out the ArcGIS controller for a KML file.

**Comment by akinspe** [comment]
Is this still an issue? Or have we addressed it?

**Comment by bpayst** [comment]
haven't had a chance to test again. switching to KML was simpler and as effective for this particular instance. I'll see if I can test again next week after doing the 1.2 update.

**Comment by akinspe** [comment]
Closed. We can reopen if this is still an issue
