### ISSUE TITLE
Campus Map search

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#3]
Browsing the map by location works fine, but search is returning an error:

Fatal error: Call to undefined method KMLPlacemark::getListItems() in /var/www/mobile/lib/Maps/MapDataController.php on line 186

**Comment by akinspe** [comment]
Unable to reproduce, can you check on the most recent master? If it still fails, we might need some config file examples to isolate.

**Comment by bpayst** [comment]
most recent master seems to have fixed this. I had noticed that in kml files without a <document> and <folder> tag I was not seeing this problem. I removed those tags from the KML files, updated to most recent code and flushed the caches and it's working fine now.
