### ISSUE TITLE
Calendar error: BYWEEKNO, BYSETPOS, WKST Not handled yet

### ISSUE THREAD

**Issue by e2xperimental** [modolabs/Kurogo-Mobile-Web#41]
Our ical feed is throwing the following error in Kurogo 1.3:

**BYWEEKNO, BYSETPOS, WKST Not handled yet**
**Fatal error:** Uncaught exception 'Exception' with message 'BYWEEKNO, BYSETPOS, WKST Not handled yet' in /www/union/applications/Kurogo/lib/Calendar/ICalendar.php:750

This is what our [site_dir]/config/calendar/feeds.ini file looks like:
`[campuscal]
TITLE              = "Campus Calendar"
BASE_URL           = "http://www.union.edu/feeds/calendar/adecalendar.ics"
HALT_ON_PARSE_ERRORS = "0"
CONTROLLER_CLASS  = "CalendarDataController"
PARSER_CLASS      = "ICSDataParser"
EVENT_CLASS       = "ICalEvent"`

Note: This is an Http iCal URL. Would it help if we used a WebCal iCal URL?

Thanks,
Erik

**Comment by akinspe** [comment]
No the URL is fine. We just have to add the support in our ICS parser

**Comment by akinspe** [comment]
This should be fixed in 1.4
