### ISSUE TITLE
Maps Module - map not center if "Map" tab isn't default

### ISSUE THREAD

**Issue by chriscronbaugh** [modolabs/Kurogo-Mobile-Web#47]
When you change the default tab in the Maps Module (or modules 
extending the Maps Module) by changing the order of the [tabs] in / 
site/[SITE]/config/map/page-detail.ini, the "Map" tab's map is no longer 
centered on the marker, but is slightly off (in my case, it was 
centered just southeast of the marker).  I'm working off of Kurogo 
1.3.

**Comment by sonya** [comment]
Chris - thanks for this ticket and your email about this a few days ago. There are a lot of UI changes in the map module in v1.4, and the tabbed interface and JavaScript base maps no longer coexist on the same screen. We're still working on map-related issues for 1.4 though, so if you manage to play around with the release candidate I'd be interested in your thoughts on that.

**Comment by chriscronbaugh** [comment]
Sonya -  thanks for the response.  I'll have to play around with the RC to see how things have changed and how they work.  I'll let you know my thoughts via the Google group.

**Comment by akinspe** [comment]
Addressed in 1.4. Please open a new issue if this is not resolved
