### ISSUE TITLE
Events parsing error

### ISSUE THREAD

**Issue by bpayst** [modolabs/Kurogo-Mobile-Web#5]
When parsing an iCal feed from Bedeworks calendar I get an error:

Fatal error: Call to a member function set_end() on a non-object in /var/www/mobile/lib/Calendar/ICalendar.php on line 439

The feed URL being used is:

http://events.unc.edu/cal/main/listEvents.do?days=7&cat=Lectures%20and%20Seminars&format=text/calendar

I am able to subscribe to this feed in other iCal applications

**Comment by akinspe** [comment]
We were not processing DURATION fields. That's been added. There is still an issue with this feed as we have to add in the parsing for BYXXX repeating events.

**Comment by bpayst** [comment]
is there an estimate of when the BYXXX fix might make it in?

**Comment by akinspe** [comment]
No estimate at this time. However you can ignore parsing errors by adding a HALT_ON_PARSE_ERRORS=0 to a given calendar feed.

**Comment by akinspe** [comment]
Support for recurring events has been added
