### ISSUE TITLE
Changing timezone affects calendar

### ISSUE THREAD

**Issue by rando128** [modolabs/Kurogo-Mobile-Web#53]
If I change the local timezone configuration to GMT+1 for instance (from the web admin), and try to reach the provided Google iCap Event Calendar (or simply go to calendar/day?type=static&calendar=events), then apache starts eating 100% of the CPU and the browser ends with a Fatal error. 

The bad side effect of this issue is that people can't use their iPad with the default Universitas setup in case they change the timezone as the calendar panel will face this problem.

To reproduce the problem:
- set a server whose OS is configured with GMT+1
- deploy Kurogo
- change the timezone from the web admin to reflect the OS timezone
- open the browser to the tablet homepage

**Comment by akinspe** [comment]
Please apply this patch, or checkout branch "issue-53". This updates our handling of events that are of different timezone to the system timezone. There was a flaw in this that caused an infinite (or at least very lengthy) loop in the code for handling recurring events.

**Comment by akinspe** [comment]
This is addressed in 1.5
