### ISSUE TITLE
Sports icons in athletics module

### ISSUE THREAD

**Issue by tsalcedo** [modolabs/Kurogo-Mobile-Web#59]
Kurogo will add an appropriate icon to individual sports based on title. However, this starts to break down for sports with two word names. For example, to make the ice hockey, cross country or field hockey icons appear, I must use a title of IceHockey, CrossCountry, FieldHockey (no spaces in the title)... The swimming and diving icon does appear without such trickery.

**Comment by akinspe** [comment]
You can actually use the ICON="XXX" option in feeds.ini this will use the images found in the athletics images folder. so you can just say ICON="icehockey" and leave your title the same.
